name: "Quicktype Action"
description: "Generate code from JSON schema using quicktype"

branding:
  label: "Quicktype"
  icon: "book"
  color: "blue"

inputs:
  source-file:
    description: "the file containing the JSON schema"
    required: true
  out-langs:
    description: "a comma separates list of output langs to generate"
    required: true
  out-dir:
    description: "the directory to output the generated code"
    required: false
    default: "."
  no-json-schema:
    description: "generate types from raw json, rather than a json-schema definition"
    required: false
    default: false

runs:
  using: "node20"
  main: "dist/index.js"
